### ISSUE TITLE
Adding pseudo-elements in available types and CSS selector grouping?

### ISSUE THREAD

**Issue by chaaals** [jofftiquez/styles.js#5]
Hi kuya @jofftiquez ! I want to contribute in this project cause I find this really interesting :>.  What do you think about adding commonly used pseudo elements like `::after` and `::before` as available types??

I also want to try and implement css selector grouping similar to this:
```
h1, h2, h3 {
// some styles
}
```

If you're up for it, I can work on this <3

**Comment by jofftiquez** [comment]
Hello @chaaals is this related to the previously accepted PR? Thanks <3

**Comment by chaaals** [comment]
> Hello @chaaals is this related to the previously accepted PR? Thanks <3

yup!! @jofftiquez

**Comment by jofftiquez** [comment]
Cool! Closing this now, thank you 💜
